name: Release to Maven Central

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
        default: '3.?.?'

jobs:
  buildpublish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Releasing jSerialComm v${{ github.event.inputs.releaseversion }}"

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Build native libraries using Docker toolchain
        uses: addnab/docker-run-action@v3
        with:
          image: fazecast/jserialcomm:builder
          options: --user root --privileged --rm -v ${{ github.workspace }}:/home/toolchain/jSerialComm
          run: /home/toolchain/compile.sh libs

      - name: Set up Java build environment
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build library using Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 8.1.1
          arguments: build

      - name: Publish library using Gradle
        uses: gradle/gradle-build-action@v2.4.2
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          SIGNING_PASSWORD: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        with:
          gradle-version: 8.1.1
          arguments: publish

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GRADLE_UPDATE_PAT }}

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GRADLE_UPDATE_PAT }}
          name: "jSerialComm v${{ github.event.inputs.releaseversion }}"
          tag: "v${{ github.event.inputs.releaseversion }}"
          body: ${{ steps.changelog.outputs.changelog }}
          commit: "master"
          artifacts: "build/libs/jSerialComm-${{ github.event.inputs.releaseversion }}.jar"
          generateReleaseNotes: false
          prerelease: false
          makeLatest: true
          draft: true

      - name: Update Javadoc library documentation
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: documentation
      - run: rm -rf documentation/binaries/* documentation/javadoc && mv build/docs/javadoc documentation/ && sed -i "s/jSerialComm-[^j]*jar/jSerialComm-${{ github.event.inputs.releaseversion }}.jar/g" documentation/index.html

      - name: Publish new library documentation
        uses: s0/git-publish-subdir-action@v2.6.0
        with:
          REPO: self
          BRANCH: gh-pages
          FOLDER: documentation
          GITHUB_TOKEN: ${{ secrets.GRADLE_UPDATE_PAT }}
          MESSAGE: "Updated docs to v${{ github.event.inputs.releaseversion }}"
